yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('', views.index, name='index'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    # Страница выхода из УЗ
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    # страница регистрации
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),

    # страница входа
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_reset_confirm'
    ),
    # страница сброса пароля
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset_form'
    ),

    # страница смены пароля
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change_form'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    # Встроенная админка Django
    path('admin/', admin.site.urls, name='admin'),
    # urls для кастомного приложения users
    path('auth/', include('users.urls', namespace='users')),
    # urls модуля для управления пользователями
    path('auth/', include('django.contrib.auth.urls')),
    # Главная страница
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="Код группы"
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = "Группу"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="Текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Группа"
    )

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ('-pub_date',)

    def __str__(self):
        return (
            f'Author: {self.author.username} Pub_date: {self.pub_date} '
            f'Group: {self.group} Text: {self.text[:50]}...'
        )

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView
# Create your views here.


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


def paginate(request, posts, posts_per_page=10):
    return Paginator(posts, posts_per_page).get_page(request.GET.get('page'))


def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': paginate(request, Post.objects.all())
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginate(request, group.posts.all())
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': paginate(request, author.posts.all())
    })


def post_detail(request, post_id):
    return render(request, 'posts/post_detail.html', {
        'post': get_object_or_404(Post, id=post_id)
    })


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form, 'post': post
        })
    form.save()
    return redirect('posts:post_detail', post_id)

yatube/users/views.py
from django.views.generic import CreateView

# Create your views here.
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Александр Лощилов, студент когорты 10 факультета Python backend-разработки.
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Использованные технологии</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django 
      </li>
      <li class="list-group-item">
        SQL
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p></p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>
        {% block title%}
            Yatube
        {% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>      
      <div class="container">
        {% block content%}
          На сим месте будет опубликована статья
        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->
<footer>
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <div class="border-top text-center py-3">
    <div class="container">
      <ul class="list-group list-group-horizontal justify-content-center">
        <li class="list-group-item" style="border: none">
          <a href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="list-group-item" style="border: none">
          <a href="{% url 'about:tech' %}">Технологии</a>
        </li>
      </ul>
    </div>
    <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>
  </div>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img\\logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <!--Статические страницы перенесены в футер-->
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name  == '' %} active{% endif %} "
                 href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:password_change_form' %} active {% endif %}  link-light"
                 href="{% url 'users:password_change_form' %}">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
                Пользователь: 
                <a href="{% url 'posts:profile' user.username %}">
                    {{ user.username }}        
                </a>    
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:login' %} active {% endif %}  link-light"
                 href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:signup' %} active {% endif %}  link-light"
                 href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
<!--Существует ли post.id?-->
{% block title %}
  {% if post %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}

{% load user_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %}Редактировать пост{% else %}Новый пост{% endif %}
          </div>
          <div class="card-body">

            <!--Валидация ошибок -->
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" action="
                {% if post %}
                  {% url 'posts:post_edit' post.id %}
                {% else %}
                  {% url 'posts:post_create' %}
                {% endif %}"
            >
              {% csrf_token %}

              <!-- Обход полей формы -->
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %}
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >

                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>

                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title%}
  Записи группы - {{ group }}
{% endblock %}

{% block content %}
  <h1>{{ group}}</h1>  
  <!-- Отображение описания для группы-->
  <h5>{{ group.description|linebreaks }}</h5>
  <hr>
  {% for post in page_obj%}    
    <ul>
      <li>
        Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.get_full_name}}        
        </a>        
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y"}}
      </li>
    </ul>
    {{ post.text|linebreaks }}
    {% if not forloop.last %}<hr>{% endif %}

  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Yatube - Главная страница
{% endblock %}

{% block content %}
  <div>
    <h1>Последние обновления на сайте</h1>

    {% for post in page_obj %}
      <ul>
        <li>
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name}}
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {{ post.text|linebreaks }}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
      {% endif %}

      {% if not forloop.last %}
        <hr>
      {% endif %}

    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <!-- если у поста есть группа -->
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a>
          </li>
        {% endif %}

        <li class="list-group-item">
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }}
          </a>
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaks }}
      </p>

      {% if user == post.author %}
        <hr>
        <div class="d-flex justify-content-end">
          <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-primary" role="button">
            Редактировать пост
          </a>
        </div>
      {% endif %}

    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
  <div>
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    <article>

      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y"}}
          </li>
        </ul>

        {{ post.text|truncatechars:300|linebreaks }}

        <p>
          <a href="{% url 'posts:post_detail' post.pk %}">
            {% if post.text|length > 300 %}
              читать продолжение
            {% else %}
              подробная информация
            {% endif %}
          </a>
        </p>

        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
        {% endif %}

        {% if not forloop.last %}
          <hr>
        {% endif %}

      {% endfor %}

    </article>
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}
          
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title%}
  Пароль изменен
{% endblock %}

{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}
  Изменение пароля
{% endblock %}

{% load user_filters %}

{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Изменить пароль
            </div>
            <div class="card-body">

              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}

              <form method="post"
                      {% if action_url %}
                    action="{% url action_url %}"
                      {% endif %}
              >
                {% csrf_token %}

                <!-- Обход полей формы -->
                {% for field in form %}
                  <div class="form-group row my-3"
                          {% if field.field.required %}
                       aria-required="true"
                          {% else %}
                       aria-required="false"
                          {% endif %}
                  >

                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>

                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Изменить пароль
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    </div>
  </main>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title%}
  Ссылка на восстановление пароля отправлена
{% endblock %}

{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}